//------------------------------------------------------------------------------
// FileName = C:\Users\amandio.ribeiro\Source\Repos\valantTest\ValantTest\Infrastructure.CrossCutting\Configuration\..\..\ValantTest\ApplicationSettings.config
// Generated at 03/16/2016 15:24:08
//
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     
//    NOTE: Please use the Add a Reference to System.Configuration assembly if 
//          you get compile errors with ConfigurationManager
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Specialized;
using System.Configuration;

namespace ValantTest.Infrastructure.CrossCutting.Configuration
{
	using System.Diagnostics.CodeAnalysis;

 /// <remarks>
 /// You can create partial class with the same name in another file to add custom properties
 /// </remarks>
 [ExcludeFromCodeCoverage]
 public static partial class Settings 
 {

		/// <summary>
		/// webpages_Version configuration value
		/// </summary>
		public static string webpages_Version 
		{
			get
			{
				return ConfigurationManager.AppSettings["webpages:Version"];
			}
		}


		/// <summary>
		/// webpages_Enabled configuration value
		/// </summary>
		public static bool webpages_Enabled 
		{
			get
			{
				return Convert.ToBoolean(ConfigurationManager.AppSettings["webpages:Enabled"]);
			}
		}


		/// <summary>
		/// ClientValidationEnabled configuration value
		/// </summary>
		public static bool ClientValidationEnabled 
		{
			get
			{
				return Convert.ToBoolean(ConfigurationManager.AppSettings["ClientValidationEnabled"]);
			}
		}


		/// <summary>
		/// UnobtrusiveJavaScriptEnabled configuration value
		/// </summary>
		public static bool UnobtrusiveJavaScriptEnabled 
		{
			get
			{
				return Convert.ToBoolean(ConfigurationManager.AppSettings["UnobtrusiveJavaScriptEnabled"]);
			}
		}


		/// <summary>
		/// ServerUri configuration value
		/// </summary>
		public static string ServerUri 
		{
			get
			{
				return ConfigurationManager.AppSettings["ServerUri"];
			}
		}


		/// <summary>
		/// HubName configuration value
		/// </summary>
		public static string HubName 
		{
			get
			{
				return ConfigurationManager.AppSettings["HubName"];
			}
		}


  

 }

 /// <remarks>
 /// You can create partial class with the same name in another file to add custom properties
 /// </remarks>
 public enum SettingsKeys 
 {

ebpages_Version,
webpages_Enabled,
ClientValidationEnabled,
UnobtrusiveJavaScriptEnabled,
ServerUri,
HubName,
  

 }
}

